{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Calendar\",\"dbrksHostName\",\"dbrksHttpPath\",\"Plant_MD\",\"Anagrafica_Audit\",\"No_Hazard_Table\",\"Area\",\"Dimensioni\",\"Fatti\",\"KPI\",\"Investimenti\",\"dbrksCatalog\",\"General_Logic\",\"Year\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.130.930.0 (24.06)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "dbrksHostName",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "description": "dbrksHostName (Databricks)",
        "expression": "\"adb-7791483519565788.8.azuredatabricks.net\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "d2b802d3-3c99-4881-9928-443db4110b05"
      },
      {
        "name": "dbrksHttpPath",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "description": "dbrksHttpPath (Databricks)",
        "expression": "\"sql/1.0/warehouses/f41b421993e3cdfe\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "456fed52-bf66-4fa1-a711-56548e14195f"
      },
      {
        "name": "dbrksCatalog",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": "\"eaap_gmp_dev\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "7924798a-023f-43be-b30d-4ed588a56fb7"
      },
      {
        "name": "General_Logic",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Databricks.Catalogs(dbrksHostName, dbrksHttpPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),",
          "    hive_metastore_Database = Source{[Name=dbrksCatalog,Kind=\"Database\"]}[Data],",
          "    gmpdltdb_Schema = hive_metastore_Database{[Name=\"gmpdltdb\",Kind=\"Schema\"]}[Data],",
          "    no_hazard_table_Table = gmpdltdb_Schema{[Name=\"no_hazard_table\",Kind=\"View\"]}[Data],",
          "    #\"Grouped Rows\" = Table.Group(no_hazard_table_Table, {\"KEY_RISK\", \"general\"}, {{\"Count\", each Table.RowCount(_), Int64.Type}}),",
          "    #\"Replaced Value\" = Table.ReplaceValue(#\"Grouped Rows\",null,\"Flag\",Replacer.ReplaceValue,{\"general\"}),",
          "    #\"Pivoted Column\" = Table.Pivot(#\"Replaced Value\", List.Distinct(#\"Replaced Value\"[general]), \"general\", \"Count\", List.Sum),",
          "    #\"Renamed Columns\" = Table.RenameColumns(#\"Pivoted Column\",{{\"\", \"Blank\"}}),",
          "    #\"Added Custom\" = Table.AddColumn(#\"Renamed Columns\", \"General_Logic\", each if [Flag] = null and [General] = null and [Blank] = 1 then \"General\" else \"Hazard\")",
          "in",
          "    #\"Added Custom\""
        ],
        "kind": "m",
        "lineageTag": "c10238ea-46eb-4c33-be8b-f01461359543"
      }
    ],
    "relationships": [
      {
        "name": "77059ec2-b386-43b7-9145-c4c099145fd5",
        "fromColumn": "CalendarDate",
        "fromTable": "Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_5ad04a72-afd5-45db-8d34-e4961e068a12"
      },
      {
        "name": "26f46e3d-14e1-4200-a92f-bd297a05d854",
        "fromColumn": "data",
        "fromTable": "Anagrafica_Audit",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_b0b6e157-4580-44c1-b84e-b8840363b15f"
      },
      {
        "name": "c3bce9ca-5c20-4ae3-9723-0ecb3d8d5d4b",
        "fromColumn": "date_answer",
        "fromTable": "Dimensioni",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_6329a821-f981-497b-b70a-fb300edfdb56"
      },
      {
        "name": "2ac9c5ea-cd03-49bc-95d6-dfd172a8d48f",
        "fromColumn": "data",
        "fromTable": "Fatti",
        "toColumn": "CalendarDate",
        "toTable": "Calendar"
      },
      {
        "name": "3489c424-3539-487f-8fac-b8da85279b50",
        "fromColumn": "id_Audit",
        "fromTable": "Fatti",
        "toColumn": "id_Audit",
        "toTable": "Anagrafica_Audit"
      },
      {
        "name": "86d6d0a1-1551-4358-9978-f70f9840b42a",
        "fromColumn": "key",
        "fromTable": "Fatti",
        "toColumn": "key",
        "toTable": "Dimensioni"
      },
      {
        "name": "77fb696f-6ace-46b9-b705-28cc35b11852",
        "fromColumn": "PlantCode",
        "fromTable": "Fatti",
        "toCardinality": "many",
        "toColumn": "PlantCode",
        "toTable": "Plant_MD"
      },
      {
        "name": "7224fee0-2bc3-9458-7303-5ab47dbe912c",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "KEY_RISK",
        "fromTable": "No_Hazard_Table",
        "toCardinality": "many",
        "toColumn": "topic",
        "toTable": "Fatti"
      },
      {
        "name": "70b4763c-215c-4820-a99e-97af059e348d",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "KEY_RISK",
        "fromTable": "Hazard_Topic",
        "toColumn": "topic",
        "toTable": "Chapter_requirement"
      },
      {
        "name": "e21f2baf-6c1d-45dd-90de-408bcdd472fc",
        "fromColumn": "closing_date",
        "fromTable": "Fatti",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c4dc0ceb-2108-4fc3-89b0-6cc04725e466"
      }
    ],
    "sourceQueryCulture": "it-IT",
    "tables": [
      {
        "name": "Calendar",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "CalendarDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "78b3c9af-09a8-4405-850a-846ad259066f",
            "sourceColumn": "CalendarDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_5ad04a72-afd5-45db-8d34-e4961e068a12"
                },
                "isDefault": true,
                "relationship": "77059ec2-b386-43b7-9145-c4c099145fd5"
              }
            ]
          },
          {
            "name": "CalendarDateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "82a07a53-6e89-4c07-a6f8-93b4fcdd3f43",
            "sourceColumn": "CalendarDateKey",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "64b2ab8c-58de-4a9c-9c6c-99bb6300c7de",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d630a385-906b-47ff-991d-da21f4ac0d4b",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "MonthName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "858221a8-6bf7-4679-9db3-131b5b00c800",
            "sourceColumn": "MonthName",
            "summarizeBy": "none"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "be9bb19e-6915-4044-8f6e-d49d9014972f",
            "sourceColumn": "Day",
            "summarizeBy": "sum"
          },
          {
            "name": "MonthNr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3ec1ac13-acd9-4fc4-a656-e61058f1231d",
            "sourceColumn": "MonthNr",
            "summarizeBy": "sum"
          },
          {
            "name": "Weekday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0d46cc75-4747-4292-ac5b-dad096ffc9a3",
            "sourceColumn": "Weekday",
            "summarizeBy": "sum"
          },
          {
            "name": "Weekyear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f53d7882-1acb-4cd2-a549-b304bd4abe8f",
            "sourceColumn": "Weekyear",
            "summarizeBy": "sum"
          },
          {
            "name": "WeekNr",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "18d899ad-eedc-4cbb-b5d2-7eb6068ab336",
            "sourceColumn": "WeekNr",
            "summarizeBy": "sum"
          },
          {
            "name": "YrDayNum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1d4ab029-761d-4513-9392-114e26bc3a31",
            "sourceColumn": "YrDayNum",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "e0a0ede3-7474-463a-8f7f-f2278894ffe3",
        "partitions": [
          {
            "name": "Calendar-cd1e50d0-48b7-4878-93cc-46b3ac66410d",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(dbrksHostName, dbrksHttpPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),",
                "    eaap_gmp_prd_Database = Source{[Name=dbrksCatalog,Kind=\"Database\"]}[Data],",
                "    gmpdltdb_Schema = eaap_gmp_prd_Database{[Name=\"gmpdltdb\",Kind=\"Schema\"]}[Data],",
                "    calendar_View = gmpdltdb_Schema{[Name=\"calendar\",Kind=\"View\"]}[Data]",
                "in",
                "    calendar_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_bf26ddf7-fd5c-4ab8-bcb3-5c2ad48d6041",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "fd36a1fc-7e04-4bec-b2a3-b8b7ce61ce34",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f5cc8c2e-5dec-4cb3-b1c3-7895538588e9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1affa4e1-8d9e-4338-9ec3-fa8d977948dd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "586131e3-0349-495c-9526-e5336d28e707",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3e7e71a3-a75c-4a48-a270-73da59676bf7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6de51d99-0c57-4a87-bd08-40673f25f16f",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "fee913ac-9db2-4abd-a3fa-133bf5b66cfb",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "26e7171e-d26c-4579-9938-5e8bc9faa840",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "873cd079-c9d1-45fd-82ad-8faa54ada8b6",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "80174e11-3a96-4c01-aa07-c24221a1f4eb",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e9907e05-8211-4a28-8485-76e8b16f0cc4",
                "ordinal": 3
              }
            ],
            "lineageTag": "d2790a17-a40f-42f0-8ae6-4e3896ed4fb6"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "061acd8f-0e88-42a6-8be7-6a754298c364",
        "partitions": [
          {
            "name": "DateTableTemplate_bf26ddf7-fd5c-4ab8-bcb3-5c2ad48d6041-f1174ca1-e9c6-4922-b288-61d7443a3ae3",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_5ad04a72-afd5-45db-8d34-e4961e068a12",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "cac66b33-9e8b-4c73-911e-d6d883fd2059",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a2c44277-fd54-42af-8bc5-e611ecf696f3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7a543ff0-aecc-486a-877f-d8952fee07f6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2a155466-987b-4029-a9d0-4eea2fa6bfde",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "12914974-6abc-4114-bb1c-a5f9e826e858",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f70c7a23-3407-4756-9132-fecee9bafc1e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3d2747e0-57f9-463f-a70d-e64ab7431b8a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "26beba1d-7256-49d3-a7a5-cefe11129bde",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "5aa64726-cbb2-4171-902f-6a96da654e30",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "588153db-16fa-4b6e-9846-9ca1b9db2d3e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b88569e9-3263-40bb-b8b8-1bc67d1aff66",
                "ordinal": 3
              }
            ],
            "lineageTag": "9befccdc-41bd-4cb5-97b3-7eb863521481"
          }
        ],
        "isHidden": true,
        "lineageTag": "1c5f497e-0926-4f3a-a97c-b296e8fa6db4",
        "partitions": [
          {
            "name": "LocalDateTable_5ad04a72-afd5-45db-8d34-e4961e068a12-bd650311-63b0-4132-b4b6-a3281be0833c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar'[CalendarDate])), 1, 1), Date(Year(MAX('Calendar'[CalendarDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Plant_MD",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "id_audit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d767c52a-d499-46e2-a48a-c0bd91cb3e98",
            "sourceColumn": "id_audit",
            "summarizeBy": "none"
          },
          {
            "name": "plant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7db5c7bd-e28a-4e03-86a2-776f41085636",
            "sourceColumn": "plant",
            "summarizeBy": "none"
          },
          {
            "name": "PlantCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fa15ea8d-75f6-4355-808b-7147dfd6db20",
            "sourceColumn": "PlantCode",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e9883cd-0627-4f61-9b93-8855795f1b82",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "CountryCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "98d027a3-05d6-4a82-9105-217c22101544",
            "sourceColumn": "CountryCode",
            "summarizeBy": "none"
          },
          {
            "name": "Cluster",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4c665199-258d-4347-80a5-f29f72e95689",
            "sourceColumn": "Cluster",
            "summarizeBy": "none"
          },
          {
            "name": "ClusterCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ea7d110-b412-4191-9d78-aae116c4728c",
            "sourceColumn": "ClusterCode",
            "summarizeBy": "none"
          },
          {
            "name": "Value_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "CALCULATE (",
              "    AVERAGE( Fatti[valore] ),",
              "    FILTER ( ALL ( FattI ),  Fatti[Plant]= Plant_MD[plant] )",
              ")"
            ],
            "formatString": "#,0.00",
            "isDataTypeInferred": true,
            "lineageTag": "55121092-f06a-458b-a76f-3d93bfeb2c28",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Cluster Compliance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "IF(Plant_MD[Value_%]<=0.25,\"0-25\",",
              "IF(Plant_MD[Value_%]<=0.5,\"25-50\",",
              "IF(Plant_MD[Value_%]<=0.75,\"50-75\",\"75-100\")))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "8625eaf9-dbf3-45e0-b1b1-dc7ca4629b56",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Plant Conc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "Plant_MD[plant] & \" - \" & Plant_MD[PlantCode]",
            "isDataTypeInferred": true,
            "lineageTag": "e2233ed3-868b-4b53-85d8-0c8e59d8acb7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "REGIONQFS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cbf0791f-cf37-4498-98f7-81603eca2cd1",
            "sourceColumn": "REGIONQFS",
            "summarizeBy": "none"
          },
          {
            "name": "REGIONCOMPANY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "76f54a11-428d-4261-8b26-1ddf1e9744d8",
            "sourceColumn": "REGIONCOMPANY",
            "summarizeBy": "none"
          },
          {
            "name": "PLant_def",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "560230bd-2da2-46ce-b458-56b2d51324a9",
            "sourceColumn": "PLant_def",
            "summarizeBy": "none"
          },
          {
            "name": "REGIONCODECOMPANY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "77686b7d-a9f7-42eb-a89d-b21e7c8b8652",
            "sourceColumn": "REGIONCODECOMPANY",
            "summarizeBy": "none"
          },
          {
            "name": "MARKET",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f257ae8-4ece-4c59-8b64-c4ed98413793",
            "sourceColumn": "MARKET",
            "summarizeBy": "none"
          },
          {
            "name": "MARKETCODE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fa3d19eb-873a-47f1-90f1-8e19708a0e4d",
            "sourceColumn": "MARKETCODE",
            "summarizeBy": "none"
          },
          {
            "name": "subplant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ddfab2d-572a-4fda-a007-22aefe5f94eb",
            "sourceColumn": "subplant",
            "summarizeBy": "none"
          },
          {
            "name": "subPlantCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f2cd2f2-a143-47dc-bf8d-f9177335f76e",
            "sourceColumn": "subPlantCode",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "64202a66-cd33-4113-8fd3-badd6c59c0a6",
        "partitions": [
          {
            "name": "Plant_MD-0661c7a7-cdc1-4f3e-a6ad-43ecf04ead19",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(dbrksHostName, dbrksHttpPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),",
                "    hive_metastore_Database = Source{[Name=dbrksCatalog,Kind=\"Database\"]}[Data],",
                "    gmpdltdb_Schema = hive_metastore_Database{[Name=\"gmpdltdb\",Kind=\"Schema\"]}[Data],",
                "    stabilimenti_Table = gmpdltdb_Schema{[Name=\"stabilimenti_test\",Kind=\"View\"]}[Data]",
                "in",
                "    stabilimenti_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Anagrafica_Audit",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "id_Audit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5da828b5-95f8-4bba-bf61-267afbfd1a3d",
            "sourceColumn": "id_Audit",
            "summarizeBy": "none"
          },
          {
            "name": "titolo_audit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8b49dbeb-d711-47a7-8c8a-2b0f21dfc5a9",
            "sourceColumn": "titolo_audit",
            "summarizeBy": "none"
          },
          {
            "name": "data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f08424b1-a6c7-4b30-899c-5ee6fd600930",
            "sourceColumn": "data",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_b0b6e157-4580-44c1-b84e-b8840363b15f"
                },
                "isDefault": true,
                "relationship": "26f46e3d-14e1-4200-a92f-bd297a05d854"
              }
            ]
          }
        ],
        "lineageTag": "75ad619a-928e-4897-a7c5-9cb7a1458a92",
        "partitions": [
          {
            "name": "Anagrafica_Audit-65b70130-59d7-4310-824e-108a61da0765",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(dbrksHostName, dbrksHttpPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),",
                "    hive_metastore_Database = Source{[Name=dbrksCatalog,Kind=\"Database\"]}[Data],",
                "    gmpdltdb_Schema = hive_metastore_Database{[Name=\"gmpdltdb\",Kind=\"Schema\"]}[Data],",
                "    anagrafica_audit_Table = gmpdltdb_Schema{[Name=\"anagrafica_audit\",Kind=\"View\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(anagrafica_audit_Table,{{\"id_Audit\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_b0b6e157-4580-44c1-b84e-b8840363b15f",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "90359ddb-7be6-4672-9c2d-55dda1dc1ef7",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6a8f98e9-7f67-48f3-9985-31ba0e841e4f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1a05d1e1-3762-4fc6-8a95-ce29a66883d1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d3dbc73f-20cc-4761-b504-ad7301e44a57",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "15cc7fbf-204f-458d-bd31-eeb8e84e920c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "180b1ee4-f46f-4549-8de4-723f094cc2a8",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "562b6eeb-5220-48c3-9e52-de3fedafa162",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "78c6999e-34d6-48b3-8ae5-15f5b0ae7474",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "41fbb12c-1033-4dfb-8ce6-9a880f3e2cc4",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d9a11a5a-85ac-475b-a10f-12ffe3352e4a",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "6845fd2c-473e-4d8c-92cd-ca2cca02d3ed",
                "ordinal": 3
              }
            ],
            "lineageTag": "44dd96b9-9d83-4294-8526-a89491df139a"
          }
        ],
        "isHidden": true,
        "lineageTag": "c20a7b56-149b-4228-9246-a7ced3b9282a",
        "partitions": [
          {
            "name": "LocalDateTable_b0b6e157-4580-44c1-b84e-b8840363b15f-ccb18795-904e-4570-85ad-41521a7b7203",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Anagrafica_Audit'[data])), 1, 1), Date(Year(MAX('Anagrafica_Audit'[data])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "No_Hazard_Table",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "requirementId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "97049784-9bdf-4ccd-8f4a-6891fcd15301",
            "sourceColumn": "requirementId",
            "summarizeBy": "none"
          },
          {
            "name": "topicId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "26c10cd3-5fd0-443c-a5bb-e74bf2555f8b",
            "sourceColumn": "topicId",
            "summarizeBy": "none"
          },
          {
            "name": "chapterId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3596758f-69ac-47d5-baff-7e4df8fa616c",
            "sourceColumn": "chapterId",
            "summarizeBy": "none"
          },
          {
            "name": "subReq",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "45b34e41-4ed8-48cd-bc52-5da5fa565b17",
            "sourceColumn": "subReq",
            "summarizeBy": "none"
          },
          {
            "name": "KEY_RISK",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dab91606-7c72-4388-836e-7e77036e730f",
            "sourceColumn": "KEY_RISK",
            "summarizeBy": "none"
          },
          {
            "name": "general",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2776bf76-0255-4868-80e4-9985b304be9c",
            "sourceColumn": "general",
            "summarizeBy": "none"
          },
          {
            "name": "Hazard",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f83ae0c3-aabc-4238-b2a4-8408df557860",
            "sourceColumn": "Hazard",
            "summarizeBy": "none"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "900f45e1-5b58-450e-b702-35a0015eb750",
            "sourceColumn": "Value",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4a8a48f1-89a5-4fc7-8334-569cf0649371",
        "partitions": [
          {
            "name": "No_Hazard_Table-50f55130-a353-471e-87a3-d29a4fa2f840",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(dbrksHostName, dbrksHttpPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),",
                "    hive_metastore_Database = Source{[Name=dbrksCatalog,Kind=\"Database\"]}[Data],",
                "    gmpdltdb_Schema = hive_metastore_Database{[Name=\"gmpdltdb\",Kind=\"Schema\"]}[Data],",
                "    no_hazard_table_Table = gmpdltdb_Schema{[Name=\"no_hazard_table\",Kind=\"View\"]}[Data],",
                "    #\"Merged Queries\" = Table.NestedJoin(no_hazard_table_Table, {\"KEY_RISK\"}, General_Logic, {\"KEY_RISK\"}, \"No_Hazard_Table (2)\", JoinKind.LeftOuter),",
                "    #\"Expanded No_Hazard_Table (2)\" = Table.ExpandTableColumn(#\"Merged Queries\", \"No_Hazard_Table (2)\", {\"General_Logic\"}, {\"General_Logic\"}),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Expanded No_Hazard_Table (2)\", \"General Logic Final\", each if [Hazard] = \"General\" and [General_Logic] = \"Hazard\" then \"Exclude\" else \"Keep\"),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Added Custom\", each ([General Logic Final] = \"Keep\")),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows\",{\"General_Logic\", \"General Logic Final\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Area",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "area",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1f79f53-5d27-46f5-ae16-7c082954ec93",
            "sourceColumn": "area",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "37f9c747-b897-49cd-8444-73d9a57f1914",
        "partitions": [
          {
            "name": "Area-3b532fd8-74b1-45c1-a35a-995242eb0783",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(dbrksHostName, dbrksHttpPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),",
                "    hive_metastore_Database = Source{[Name=dbrksCatalog,Kind=\"Database\"]}[Data],",
                "    gmpdltdb_Schema = hive_metastore_Database{[Name=\"gmpdltdb\",Kind=\"Schema\"]}[Data],",
                "    area_Table = gmpdltdb_Schema{[Name=\"area\",Kind=\"View\"]}[Data]",
                "in",
                "    area_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dimensioni",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0c62bd0d-30e5-419f-b9a1-8570ee0064c9",
            "sourceColumn": "id",
            "summarizeBy": "sum"
          },
          {
            "name": "id_Audit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "95da6da3-eb39-4229-a7d9-f7d74f97667a",
            "sourceColumn": "id_Audit",
            "summarizeBy": "none"
          },
          {
            "name": "key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3b5cea69-d423-43c7-9593-bc637cd54d59",
            "sourceColumn": "key",
            "summarizeBy": "none"
          },
          {
            "name": "titolo_audit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb5b69b2-cad3-48e7-9e11-ba9fbddf6205",
            "sourceColumn": "titolo_audit",
            "summarizeBy": "none"
          },
          {
            "name": "Titolo_Paragraph",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "65055308-57b9-4a55-92ff-6ea049057489",
            "sourceColumn": "Titolo_Paragraph",
            "summarizeBy": "sum"
          },
          {
            "name": "stabilimento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6b9ac6e5-bd7c-456e-8afb-632427f6cb59",
            "sourceColumn": "stabilimento",
            "summarizeBy": "none"
          },
          {
            "name": "gmp_release",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "246c4e4f-bccb-477a-821c-c26fa8def728",
            "sourceColumn": "gmp_release",
            "summarizeBy": "sum"
          },
          {
            "name": "chapter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "60ed4582-7475-42e6-8a70-2e07b11deb9e",
            "sourceColumn": "chapter",
            "summarizeBy": "none"
          },
          {
            "name": "requirement",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "99d5d137-24d4-4c07-a869-2c16d9bb4b6f",
            "sourceColumn": "requirement",
            "summarizeBy": "none"
          },
          {
            "name": "must_should",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0dd42213-a684-4bb8-9aa2-759aa48fe2b5",
            "sourceColumn": "must_should",
            "summarizeBy": "none"
          },
          {
            "name": "structural_managerial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e7fdbc44-07dc-4682-a6a1-3d40ae2c032d",
            "sourceColumn": "structural_managerial",
            "summarizeBy": "none"
          },
          {
            "name": "topic",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d933d186-45b7-474d-841d-b870f50e6e19",
            "sourceColumn": "topic",
            "summarizeBy": "none"
          },
          {
            "name": "Paragraph",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "21037c8b-57cb-4770-90f8-4d8f835c0888",
            "sourceColumn": "Paragraph",
            "summarizeBy": "none"
          },
          {
            "name": "ParagraphComplete",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a85d235-7089-48b2-9c95-68ac6fcbcd7e",
            "sourceColumn": "ParagraphComplete",
            "summarizeBy": "none"
          },
          {
            "name": "requirement_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4b0b3047-a46e-4d60-8978-b62718f49d18",
            "sourceColumn": "requirement_id",
            "summarizeBy": "none"
          },
          {
            "name": "sub_req",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "724e0d64-e64a-424b-a903-4b525bead9c5",
            "sourceColumn": "sub_req",
            "summarizeBy": "none"
          },
          {
            "name": "level_of_priority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5474dee5-3ccc-4e55-a537-673fa04daac6",
            "sourceColumn": "level_of_priority",
            "summarizeBy": "none"
          },
          {
            "name": "1_raw_packaging_material_storage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "23d04402-8854-441f-a82b-472023c41ae9",
            "sourceColumn": "1_raw_packaging_material_storage",
            "summarizeBy": "none"
          },
          {
            "name": "2_production_area",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dddf7415-0793-4bf9-bdf1-6c7ebbdcaa9d",
            "sourceColumn": "2_production_area",
            "summarizeBy": "none"
          },
          {
            "name": "3_packaging_area",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c092307-b759-4173-806a-cb8aefd1bc6f",
            "sourceColumn": "3_packaging_area",
            "summarizeBy": "none"
          },
          {
            "name": "4_finished_product_warehouse",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aaedcbc1-d390-4850-ae25-15c55f92bdc1",
            "sourceColumn": "4_finished_product_warehouse",
            "summarizeBy": "none"
          },
          {
            "name": "5_services_area_facilities_external_area",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f84e46fd-2b6c-4705-ab34-98fcff4baa27",
            "sourceColumn": "5_services_area_facilities_external_area",
            "summarizeBy": "sum"
          },
          {
            "name": "status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b16c282b-0698-4e72-a479-247d4adcf3dc",
            "sourceColumn": "status",
            "summarizeBy": "none"
          },
          {
            "name": "note",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d0f6f32b-c720-49d3-9fd6-252c6f763aa4",
            "sourceColumn": "note",
            "summarizeBy": "none"
          },
          {
            "name": "date_answer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "46f9e617-7033-40cb-93bb-c9437e52bf2e",
            "sourceColumn": "date_answer",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_6329a821-f981-497b-b70a-fb300edfdb56"
                },
                "isDefault": true,
                "relationship": "c3bce9ca-5c20-4ae3-9723-0ecb3d8d5d4b"
              }
            ]
          },
          {
            "name": "data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "214829cc-36ff-4f51-af31-b616930b2860",
            "sourceColumn": "data",
            "summarizeBy": "sum"
          },
          {
            "name": "capitolo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c4a04587-e11c-4614-ac5c-c1ada8507919",
            "sourceColumn": "capitolo",
            "summarizeBy": "none"
          },
          {
            "name": "English_description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4db7d056-50f7-4e42-b850-7b92ff1b47ed",
            "sourceColumn": "English_description",
            "summarizeBy": "none"
          },
          {
            "name": "English_paragrafo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7348513-7ba7-47b3-b4e2-f4bb4a7c6db1",
            "sourceColumn": "English_paragrafo",
            "summarizeBy": "none"
          },
          {
            "name": "penalita_massima",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "96c1aab3-5e50-4c1c-b03b-42ec63dfe5b1",
            "sourceColumn": "penalita_massima",
            "summarizeBy": "sum"
          },
          {
            "name": "Chapter_Conc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "Dimensioni[chapter] & \" - \" & Dimensioni[capitolo]",
            "isDataTypeInferred": true,
            "lineageTag": "33041afd-d194-40da-95e5-7a95c3c778d3",
            "sortByColumn": "Chapter_Value",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Requirement_conc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "Dimensioni[topic]&\" - \"& Dimensioni[English_description]",
            "isDataTypeInferred": true,
            "lineageTag": "1554f4bb-8ad2-4b89-a9c3-d48a2bd6ba97",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "topicDetails",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "72ba5b51-89b0-4172-9512-d61b0ea8c1a0",
            "sourceColumn": "topicDetails",
            "summarizeBy": "sum"
          },
          {
            "name": "Chapter_Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "dataType": "double",
            "expression": "VALUE(Dimensioni[chapter])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "25cd4764-e30f-4146-8277-6cb3fa0f108e",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "158afc1a-390f-44af-a020-e59d1ec55226",
        "partitions": [
          {
            "name": "Dimensioni-ad489fb0-b403-49d6-8856-a8f0eb3991c5",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(dbrksHostName, dbrksHttpPath, [Catalog=null, Database=null, EnableQueryResultDownload=\"0\", EnableExperimentalFlagsV1_1_0=null]),",
                "    eaap_gmp_prd_Database = Source{[Name=dbrksCatalog,Kind=\"Database\"]}[Data],",
                "    gmpdltdb_Schema = eaap_gmp_prd_Database{[Name=\"gmpdltdb\",Kind=\"Schema\"]}[Data],",
                "    dimensioni_View = gmpdltdb_Schema{[Name=\"dimensioni\",Kind=\"View\"]}[Data]",
                "in",
                "    dimensioni_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_6329a821-f981-497b-b70a-fb300edfdb56",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "682d8a24-bac9-4320-a5b1-dd4324dfc2f9",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "500d67f2-2f9c-43fe-81e6-fbdaba708000",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "55e62064-d990-40bf-b91d-005f021fe692",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6fdf5386-6126-435e-8a54-99feb6a1c43c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6011730a-1a97-40d4-8afe-4dde0ebe228e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "aca13237-06f2-4b7c-bd42-051694d5e37b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2c7f746b-6eeb-4ef5-aac9-c588c6991895",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "c2d65519-21ad-48c7-a016-52b878617579",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "45db89cc-7603-46fb-8761-c73a90769ce8",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "e6b5003a-b6c7-4b41-b6d6-bbd7d19df538",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "8e2c53f1-1409-4d7a-9496-f480756c866d",
                "ordinal": 3
              }
            ],
            "lineageTag": "a0b2d86d-759c-46f7-b2ab-bf7bc9b9e0cc"
          }
        ],
        "isHidden": true,
        "lineageTag": "1dc08624-aada-4f26-b159-52b9a1ecf77f",
        "partitions": [
          {
            "name": "LocalDateTable_6329a821-f981-497b-b70a-fb300edfdb56-57639462-18b5-41b2-ba0d-13850e746079",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Dimensioni'[date_answer])), 1, 1), Date(Year(MAX('Dimensioni'[date_answer])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Fatti",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04c12d5b-44fb-4211-8e5d-5b67992ff994",
            "sourceColumn": "key",
            "summarizeBy": "none"
          },
          {
            "name": "id_Audit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5c5fc534-1c77-48b7-ba34-d955e35085e4",
            "sourceColumn": "id_Audit",
            "summarizeBy": "none"
          },
          {
            "name": "Plant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "60b0b7e9-fbff-40c5-ab49-e3214fb7526e",
            "sourceColumn": "Plant",
            "summarizeBy": "none"
          },
          {
            "name": "gmp_release",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eb319baf-3e1d-4cba-847c-b0c4d439ccce",
            "sourceColumn": "gmp_release",
            "summarizeBy": "sum"
          },
          {
            "name": "must_should",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dd514397-9529-4ea9-83a3-27d6a57c92e3",
            "sourceColumn": "must_should",
            "summarizeBy": "none"
          },
          {
            "name": "level_of_priority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9bf258e0-d600-4f16-a38c-64c95f773066",
            "sourceColumn": "level_of_priority",
            "summarizeBy": "none"
          },
          {
            "name": "KEY_Area",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d555f35d-bf60-44f5-b351-f761714f8ef5",
            "sourceColumn": "KEY_Area",
            "summarizeBy": "none"
          },
          {
            "name": "topic",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aed08541-c657-4ba7-a0c1-962f26ff7f9c",
            "sourceColumn": "topic",
            "summarizeBy": "none"
          },
          {
            "name": "data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "842912c7-f874-4597-908a-80738b8d06db",
            "sourceColumn": "data",
            "summarizeBy": "none"
          },
          {
            "name": "area",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2119eadb-7b25-4551-8ab5-008fe184a886",
            "sourceColumn": "area",
            "summarizeBy": "none"
          },
          {
            "name": "valore",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "lineageTag": "1db798fb-9879-4281-a2f9-4f20ae318245",
            "sourceColumn": "valore",
            "summarizeBy": "sum"
          },
          {
            "name": "penalita",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1983456e-4810-4219-8ec3-6366e31e7725",
            "sourceColumn": "penalita",
            "summarizeBy": "sum"
          },
          {
            "name": "conformita_ponderata",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0.0000",
            "lineageTag": "f609ebd5-705a-4644-a893-1680c2887c7d",
            "sourceColumn": "conformita_ponderata",
            "summarizeBy": "sum"
          },
          {
            "name": "media",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8b6f6ab4-78d6-48ce-86a7-ae50f31e865c",
            "sourceColumn": "media",
            "summarizeBy": "sum"
          },
          {
            "name": "media_con_penalita",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d18da5e6-196f-4746-92a4-d1a7768d8125",
            "sourceColumn": "media_con_penalita",
            "summarizeBy": "sum"
          },
          {
            "name": "media_singolo_requisito",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1db20265-ea19-4011-a6bc-0a1317c823f5",
            "sourceColumn": "media_singolo_requisito",
            "summarizeBy": "sum"
          },
          {
            "name": "media_singolo_requisito_con_penalita",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9e96c0b9-a2e8-41c6-9f82-4e9c3e5f7d50",
            "sourceColumn": "media_singolo_requisito_con_penalita",
            "summarizeBy": "sum"
          },
          {
            "name": "Compliance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF(DIVIDE(Fatti[valore],100) <>1,\"Not Compliant\",\"Compliant\")",
            "isDataTypeInferred": true,
            "lineageTag": "f724f462-93aa-445d-a7cb-08ede12db5c0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Cluster Compliance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF (",
              "    Fatti[Media_Aritmetica] <= 25,",
              "    \"0-25\",",
              "    IF (",
              "        Fatti[Media_Aritmetica] <= 50,",
              "        \"25-50\",",
              "        IF ( Fatti[Media_Aritmetica] <= 75, \"50-75\", \"75-100\" )",
              "    )",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "7f9fc53b-1216-476a-ba82-a4d7fcaf7a45",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Valore_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "double",
            "expression": "DIVIDE( Fatti[valore] , 100)",
            "formatString": "0.00%;-0.00%;0.00%",
            "isDataTypeInferred": true,
            "lineageTag": "4db8ebb2-dc97-4ef6-acfb-532227707d65",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Penalit_Massima",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "IF (",
              "    Fatti[must_should] = \"Must\"",
              "        && Fatti[level_of_priority] = \"High\",",
              "    0.6,",
              "    IF ( Fatti[must_should] = \"Must\" && Fatti[level_of_priority] = \"Low\", 0.3, 0 )",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "db1ea0ea-a4b1-4841-8819-d28a42840982",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Media_Aritmetica",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "CALCULATE(AVERAGE(Fatti[valore]), FILTER(Fatti, Fatti[key] = EARLIER(Fatti[key]) && Fatti[id_Audit] = EARLIER(Fatti[id_Audit]) && Fatti[Plant] = EARLIER(Fatti[Plant]) && Fatti[topic] = EARLIER(Fatti[topic])))"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "3a94629c-a3ae-429b-b6ae-87cd55ad0cdf",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "PlantCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e07901a6-2946-4c02-923b-3708ae66b1a5",
            "sourceColumn": "PlantCode",
            "summarizeBy": "none"
          },
          {
            "name": "PlantDesc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "91f695ae-f020-4697-944b-a3298ca8c494",
            "sourceColumn": "PlantDesc",
            "summarizeBy": "none"
          },
          {
            "name": "Chapter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "RELATED(Dimensioni[Chapter_Conc])",
            "isDataTypeInferred": true,
            "lineageTag": "bb57bef6-2d7c-4e5e-9f5d-01f0d2027a91",
            "sortByColumn": "Chapter_Value",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Chapter_Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "dataType": "double",
            "expression": "RELATED(Dimensioni[Chapter_Value])",
            "formatString": "#,0",
            "isDataTypeInferred": true,
            "lineageTag": "a159f1d7-0175-436e-a26f-ea91d74a5677",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Structural_Managerial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "RELATED(Dimensioni[structural_managerial])",
            "isDataTypeInferred": true,
            "lineageTag": "e425f1cd-44e7-42a4-8e16-26f9b0c62841",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Paragraph",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "RELATED(Dimensioni[Paragraph])",
            "isDataTypeInferred": true,
            "lineageTag": "b3e15de9-fc6a-4787-969c-efa574de2447",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "subplantcode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bc24a1d2-e59e-4a89-8344-192f5b96b284",
            "sourceColumn": "subplantcode",
            "summarizeBy": "none"
          },
          {
            "name": "subplant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eaba7af5-30f0-4764-b2b4-01b215dd920e",
            "sourceColumn": "subplant",
            "summarizeBy": "none"
          },
          {
            "name": "closing_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "1cf45a22-fca4-4325-8d46-ee8ff252c7b8",
            "sourceColumn": "closing_date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_c4dc0ceb-2108-4fc3-89b0-6cc04725e466"
                },
                "isDefault": true,
                "relationship": "e21f2baf-6c1d-45dd-90de-408bcdd472fc"
              }
            ]
          },
          {
            "name": "weight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f4d5f8ab-a346-4b2e-8759-b5ac73173b69",
            "sourceColumn": "weight",
            "summarizeBy": "sum"
          },
          {
            "name": "updated_conformita",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cd3cb4ff-6a66-4dee-9745-0230b1adebf4",
            "sourceColumn": "updated_conformita",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "4a4c9cf7-9d7a-4fb2-9e9a-040ef9ba21e9",
        "measures": [
          {
            "name": "test",
            "expression": "EARLIER(Fatti[key])",
            "lineageTag": "5bee971a-fbf2-4959-9f67-278c4ffc501c"
          }
        ],
        "partitions": [
          {
            "name": "Fatti-7e94b9b7-bc88-4c6c-bb34-eda85b665bc6",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(dbrksHostName, dbrksHttpPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null, EnableQueryResultDownload=\"0\"]),",
                "    hive_metastore_Database = Source{[Name=dbrksCatalog,Kind=\"Database\"]}[Data],",
                "    gmpdltdb_Schema = hive_metastore_Database{[Name=\"gmpdltdb\",Kind=\"Schema\"]}[Data],",
                "    fatti_Table = gmpdltdb_Schema{[Name=\"fatti_test_1\",Kind=\"View\"]}[Data],",
                "    #\"Divided Column\" = Table.TransformColumns(fatti_Table, {{\"updated_conformita\", each _ / 100, type number}})",
                "in",
                "    #\"Divided Column\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "KPI",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "lineageTag": "37163aa1-f41a-4896-b20e-2740710ef2cc",
        "measures": [
          {
            "name": "% Compliant",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR MediaCOMP =",
              "    CALCULATE ( [Media Aritmetica], 'Fatti'[Compliance] IN { \"Compliant\" } )",
              "VAR final =  CALCULATE ( MediaCOMP / [Media Aritmetica] )",
              "",
              "RETURN CALCULATE(final,Dimensioni[data] = SELECTEDVALUE('Year'[data]),REMOVEFILTERS(Dimensioni[data]))"
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "3234dfb5-cb89-496f-9ba7-8f2ab7047a9c"
          },
          {
            "name": "Weighted Avg Score",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "VAR countplant = CALCULATE(DISTINCTCOUNT(Fatti[PlantCode]),NOT(ISBLANK(Fatti[PlantCode])))",
              "VAR final=SUMX(SUMMARIZE(Fatti,Fatti[PlantCode]),[Weighted Avg Score_closing])",
              "",
              "RETURN IF(HASONEVALUE(Fatti[PlantCode]),final,DIVIDE(final,countplant))",
              "",
              "/*VAR TableAux =",
              "    SUMMARIZE (",
              "        Fatti,",
              "        Fatti[id_Audit],",
              "        Fatti[Area],",
              "        \"Score Aggregato per Area\", AVERAGE ( Fatti[conformita_ponderata] )",
              "    )",
              "RETURN",
              "IF (",
              "        HASONEVALUE ( Fatti[area] ),",
              "        AVERAGE ( Fatti[conformita_ponderata] ),",
              "        AVERAGEX ( TableAux, [Score Aggregato per Area] )",
              "    ) */"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "453b9bdb-b2b2-4133-b30a-4fbca6511e05"
          },
          {
            "name": "Media Aritmetica",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "SUMX(SUMMARIZE(Fatti,Fatti[PlantCode]),[Media Aritmetica_closing])",
              "",
              "/*",
              "",
              "VAR _TempTable =",
              "    SUMMARIZE (",
              "        Fatti,",
              "        Fatti[id_Audit],",
              "        Fatti[topic],",
              "        Fatti[key],",
              "        Fatti[Plant],",
              "        \"Media\", AVERAGE ( Fatti[valore] )",
              "    )",
              "",
              "",
              "RETURN",
              "    COUNTROWS ( _TempTable ) */"
            ],
            "formatString": "0",
            "lineageTag": "ff36e1cd-686b-4756-bbc7-d4c7edb30138"
          },
          {
            "name": "Color_%_Penalized",
            "expression": [
              "",
              "VAR MEDIA_PENALIZZATO = [Weighted Avg Score]",
              "RETURN",
              "    (",
              "        SWITCH (",
              "            TRUE (),",
              "            MEDIA_PENALIZZATO >= 0.75, \"#47B15B\",",
              "            MEDIA_PENALIZZATO <= 0.50, \"#E66C37\",",
              "            \"#F6D956\"",
              "        )",
              "    )"
            ],
            "lineageTag": "21497fba-1f58-4fc4-8144-3e43bd14e25f"
          },
          {
            "name": "% Cluster",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "VAR final = DIVIDE ([Media Aritmetica],CALCULATE ( [Media Aritmetica], ALL ( Fatti[Cluster Compliance] ) ))",
              "",
              "RETURN CALCULATE(final,Dimensioni[data] = SELECTEDVALUE('Year'[data]),REMOVEFILTERS(Dimensioni[data]))",
              "/*",
              "DIVIDE (",
              "    [Media Aritmetica],",
              "    CALCULATE ( [Media Aritmetica], ALL ( Fatti[Cluster Compliance] ) )",
              ") */"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "6daf43f7-b989-48b4-b64c-69c257abcc0b"
          },
          {
            "name": "Average of score %",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "var final = DIVIDE ( AVERAGE ( Fatti[valore] ), 100 )",
              "RETURN",
              "CALCULATE(final,Dimensioni[data] = SELECTEDVALUE('Year'[data]),REMOVEFILTERS(Dimensioni[data]))"
            ],
            "lineageTag": "5e195cc5-d1e4-47fc-93bd-e0e6ac2594fd"
          },
          {
            "name": "Average of Value for Must",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Cross Analysis",
            "expression": [
              "",
              "var final = CALCULATE ( [Weighted Avg Score], 'Dimensioni'[must_should] IN { \"Must\" } )",
              "",
              "RETURN CALCULATE(final,Dimensioni[data] = SELECTEDVALUE('Year'[data]),REMOVEFILTERS(Dimensioni[data]))"
            ],
            "formatString": "0",
            "lineageTag": "397d1fb0-efe2-44c9-b693-277abf82b58d"
          },
          {
            "name": "Average of Value for Should",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Cross Analysis",
            "expression": [
              "",
              "var final = CALCULATE ( [Weighted Avg Score], 'Dimensioni'[must_should] IN { \"Should\" } )",
              "",
              "RETURN CALCULATE(final,Dimensioni[data] = SELECTEDVALUE('Year'[data]),REMOVEFILTERS(Dimensioni[data]))"
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "73ab3b27-2ee1-446f-b71a-3d0374355c48"
          },
          {
            "name": "Average of Value for High",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Cross Analysis",
            "expression": [
              "",
              "var final = CALCULATE (",
              "    [Weighted Avg Score],",
              "    'Dimensioni'[level_of_priority] IN { \"High\" }",
              ")",
              "",
              "RETURN CALCULATE(final,Dimensioni[data] = SELECTEDVALUE('Year'[data]),REMOVEFILTERS(Dimensioni[data]))"
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "72713d6a-da34-46b0-a63b-406fd214316e"
          },
          {
            "name": "Average of Value for Low",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Cross Analysis",
            "expression": [
              "",
              "var final = CALCULATE ( [Weighted Avg Score], 'Dimensioni'[level_of_priority] IN { \"Low\" } )",
              "",
              " RETURN CALCULATE(final,Dimensioni[data] = SELECTEDVALUE('Year'[data]),REMOVEFILTERS(Dimensioni[data]))"
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "51e9fb6b-57e0-4613-bb8b-935806e3c053"
          },
          {
            "name": "Must + High",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Cross Analysis",
            "expression": [
              "",
              "CALCULATE (",
              "    [Average of score %],",
              "    Dimensioni[must_should] = \"Must\",",
              "    Dimensioni[level_of_priority] = \"High\"",
              ")"
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "0ec2fd74-6e4e-4185-a4f0-65943532ef21"
          },
          {
            "name": "Must + Low",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "Cross Analysis",
            "expression": [
              "",
              "CALCULATE (",
              "    [Average of score %],",
              "    Dimensioni[must_should] = \"Must\",",
              "    Dimensioni[level_of_priority] = \"Low\"",
              ")"
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "lineageTag": "d7f9fccf-c556-4c80-85dd-baf742c2759a"
          },
          {
            "name": "Hazard_over_75",
            "expression": [
              "",
              "VAR _TempTable =",
              "    FILTER (",
              "        ADDCOLUMNS (",
              "            SUMMARIZE ( No_Hazard_Table, No_Hazard_Table[Hazard] ),",
              "            \"Weigthed\", [Weighted Avg Score]",
              "        ),",
              "        [Weigthed] > 0.75",
              "    )",
              "VAR _Total =",
              "    COUNTROWS ( _TempTable )",
              "RETURN",
              "    IF ( ISBLANK ( _Total ), 0, _Total )"
            ],
            "formatString": "0",
            "lineageTag": "b551becb-9d9c-4ac3-8edb-c187c515defe"
          },
          {
            "name": "Hazard_under_75",
            "expression": [
              "",
              "VAR _TempTable =",
              "    FILTER (",
              "        ADDCOLUMNS (",
              "            SUMMARIZE ( No_Hazard_Table, No_Hazard_Table[Hazard] ),",
              "            \"Weigthed\", [Weighted Avg Score]",
              "        ),",
              "        [Weigthed] <= 0.75",
              "    )",
              "VAR _Total =",
              "    COUNTROWS ( _TempTable )",
              "RETURN",
              "    IF ( ISBLANK ( _Total ), 0, _Total )"
            ],
            "formatString": "0",
            "lineageTag": "9f212f94-62f6-4f4b-bbb2-8d4f5f802284"
          },
          {
            "name": "Area_over_75",
            "expression": [
              "",
              "VAR _TempTable =",
              "    FILTER (",
              "        ADDCOLUMNS ( SUMMARIZE ( Fatti, Fatti[area] ), \"Weigthed\", [Weighted Avg Score] ),",
              "        [Weigthed] > 0.75",
              "    )",
              "VAR _Total =",
              "    COUNTROWS ( _TempTable )",
              "RETURN",
              "    IF ( ISBLANK ( _Total ), 0, _Total )"
            ],
            "formatString": "0",
            "lineageTag": "fe6680ac-e29a-45dc-bc49-5bcad40bebc6"
          },
          {
            "name": "Area_under_75",
            "expression": [
              "",
              "VAR _TempTable =",
              "    FILTER (",
              "        ADDCOLUMNS ( SUMMARIZE ( Fatti, Fatti[area] ), \"Weigthed\", [Weighted Avg Score] ),",
              "        [Weigthed] <= 0.75",
              "    )",
              "VAR _Total =",
              "    COUNTROWS ( _TempTable )",
              "RETURN",
              "    IF ( ISBLANK ( _Total ), 0, _Total )"
            ],
            "formatString": "0",
            "lineageTag": "f824f3b0-a010-4032-9d82-979f29d72dbe"
          },
          {
            "name": "Plant_over_75",
            "expression": [
              "",
              "VAR _TempTable =",
              "    FILTER (",
              "        ADDCOLUMNS (",
              "            SUMMARIZE ( Fatti, Fatti[PlantCode] ),",
              "            \"Weigthed\", [Weighted Avg Score]",
              "        ),",
              "        [Weigthed] > 0.75",
              "    )",
              "VAR _Total =",
              "    COUNTROWS ( _TempTable )",
              "RETURN",
              "    IF ( ISBLANK ( _Total ), 0, _Total )"
            ],
            "formatString": "0",
            "lineageTag": "7172680c-c55c-414a-8baa-737f87e7a795"
          },
          {
            "name": "Plant_under_75",
            "expression": [
              "",
              "VAR _TempTable =",
              "    FILTER (",
              "        ADDCOLUMNS (",
              "            SUMMARIZE ( Fatti, Fatti[PlantCode] ),",
              "            \"Weigthed\", [Weighted Avg Score]",
              "        ),",
              "        [Weigthed] <= 0.75",
              "    )",
              "VAR _Total =",
              "    COUNTROWS ( _TempTable )",
              "RETURN",
              "    IF ( ISBLANK ( _Total ), 0, _Total )"
            ],
            "formatString": "0",
            "lineageTag": "9f7115ec-83a6-44c8-a977-ed06db2a0e93"
          },
          {
            "name": "Conformita_What_if_Scenario",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "What_If_Scenario",
            "expression": [
              "",
              "VAR Valore_Simulato =",
              "    IF (",
              "        ISBLANK ( AVERAGE ( Fatti[Valore_%] ) ),",
              "        BLANK (),",
              "        CALCULATE (",
              "            AVERAGE ( Fatti[Valore_%] ) + 'Miglioramento_%'[Miglioramento_% Value]",
              "        )",
              "    )",
              "RETURN",
              "    IF (",
              "        Valore_Simulato > 100,",
              "        1,",
              "        IF (",
              "            'Miglioramento_%'[Miglioramento_% Value] = 0,",
              "            [Weighted Avg Score],",
              "            Valore_Simulato",
              "        )",
              "    )"
            ],
            "lineageTag": "b796cf42-4310-47ab-ac7c-2c4d05147dff"
          },
          {
            "name": "%_Penalita_What_if_Scenario",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "What_If_Scenario",
            "expression": [
              "",
              "VAR Part_1 =",
              "    ( [Conformita_What_if_Scenario] * -1 )",
              "        * AVERAGE ( Fatti[Penalit_Massima] )",
              "VAR Part_2 =",
              "    AVERAGE ( Fatti[Penalit_Massima] )",
              "RETURN",
              "    Part_1 + Part_2"
            ],
            "formatString": "#,0.00",
            "lineageTag": "945a3a9b-2eef-487e-bd7f-116652af431a"
          },
          {
            "name": "Valore_Ponderato_What_if_scenario",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "What_If_Scenario",
            "expression": [
              "",
              "VAR Result =",
              "    IF (",
              "        'Miglioramento_%'[Miglioramento_% Value] = 0,",
              "        [Weighted Avg Score],",
              "        [Conformita_What_if_Scenario] * ( 1 - [%_Penalita_What_if_Scenario] )",
              "    )",
              "VAR Result_ =",
              "    IF ( Result > 1, 1, Result )",
              "RETURN",
              "    Result_"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "511b7517-4848-420e-a529-e96fca4d03f9"
          },
          {
            "name": "Abs Increase",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "displayFolder": "What_If_Scenario",
            "expression": [
              "",
              "IF (",
              "    [Area_Chapter_Level_Simulation] - [Weighted Avg Score] <= 0.000001,",
              "    BLANK (),",
              "    [Area_Chapter_Level_Simulation] - [Weighted Avg Score]",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "bd69d469-d360-4d9d-8394-863b2c22aff5"
          },
          {
            "name": "Report Filter",
            "expression": [
              "",
              "COUNTROWS ( Fatti )"
            ],
            "formatString": "0",
            "lineageTag": "f3a4e687-d701-45dd-af78-da594ba8fa24"
          },
          {
            "name": "Abs Increase_Hazard",
            "displayFolder": "What_If_Scenario",
            "expression": [
              "",
              "IF (",
              "    [Hazard_Level_Simulation] - [Weighted Avg Score] = 0,",
              "    BLANK (),",
              "    [Hazard_Level_Simulation] - [Weighted Avg Score]",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e7a8865f-02ff-435e-ad80-ca0ab9746946"
          },
          {
            "name": "Filter_Unrelated",
            "displayFolder": "What_If_Scenario",
            "expression": [
              "",
              "CALCULATE (",
              "    COUNTROWS ( Dimensioni ),",
              "    KEEPFILTERS (",
              "        TREATAS ( VALUES ( Chapter_requirement[topic] ), Dimensioni[topic] )",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "33dd6252-d30c-4f4a-b90d-3b565a136111"
          },
          {
            "name": "Report_Fatti_What_If_Filter",
            "displayFolder": "What_If_Scenario",
            "expression": [
              "",
              "CALCULATE (",
              "    COUNTROWS ( Fatti ),",
              "    KEEPFILTERS ( TREATAS ( VALUES ( Chapter_requirement[topic] ), Fatti[topic] ) )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "a47e54be-6ecb-4001-a465-a8b6118b9b2e"
          },
          {
            "name": "Area_Chapter_Level_Simulation",
            "displayFolder": "What_If_Scenario",
            "expression": [
              "",
              "IF (",
              "    ISINSCOPE ( Fatti[Chapter_Value]),",
              "    [Chapter_Level_Simulation] ,",
              "    AVERAGEX ( Fatti, [Chapter_Level_Simulation] )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "c27ee989-2481-476b-92c6-d8a3ab5c8ca8"
          },
          {
            "name": "Chapter_Level_Simulation",
            "displayFolder": "What_If_Scenario",
            "expression": [
              "",
              "IF (",
              "    SELECTEDVALUE ( Fatti[Chapter_Value] )",
              "        IN VALUES ( Chapter_requirement[Chapter_Value] ),",
              "    [Simulated_Score_%_Final],",
              "    [Weighted Avg Score]",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "ca7e41bb-eece-4ef5-afaa-cfff34bfd8e2"
          },
          {
            "name": "Hazard_Flag",
            "displayFolder": "What_If_Scenario",
            "expression": [
              "",
              "VAR Values_ =",
              "    VALUES ( Chapter_requirement[topic] )",
              "VAR Hazard_ =",
              "    VALUES ( Hazard_Topic[Hazard])",
              "VAR Temptable =",
              "    ADDCOLUMNS (",
              "        SUMMARIZE (",
              "            No_Hazard_Table,",
              "            No_Hazard_Table[Hazard],",
              "            No_Hazard_Table[KEY_RISK]",
              "        ),",
              "        \"Value\", IF ( No_Hazard_Table[KEY_RISK] IN Values_ && No_Hazard_Table[Hazard] IN Hazard_, 1, 0 )",
              "    )",
              "RETURN",
              "    MAXX ( Temptable, [Value] ) "
            ],
            "formatString": "0",
            "lineageTag": "e354574b-59ce-4b43-8ed7-656a58c2adca"
          },
          {
            "name": "Hazard_Level_Simulation",
            "displayFolder": "What_If_Scenario",
            "expression": [
              "",
              "IF (",
              "    [Hazard_Flag] = 1",
              "        && [Simulation_Aggregated] > [Weighted Avg Score],",
              "    [Simulation_Aggregated] ,",
              "    [Weighted Avg Score]",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "c01d8100-ba84-439b-9bc3-6132f4c38ca7"
          },
          {
            "name": "Simulated_Score_%_Final",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "What_If_Scenario",
            "expression": [
              "",
              "VAR Topic_Selez =",
              "    VALUES ( Chapter_requirement[topic] )",
              "VAR Area_Selez =",
              "    VALUES ( Area[area] )",
              "VAR Type_managerial = ",
              "    VALUES(Chapter_requirement[structural_managerial])",
              "VAR Must_Should = ",
              "    VALUES(Chapter_requirement[must_should])",
              "VAR Priority = ",
              "    VALUES(Chapter_requirement[level_of_priority])",
              "VAR Chapter = ",
              "    VALUES(Chapter_requirement[Chapter_Value])",
              "VAR Paragraph = ",
              "    VALUES(Fatti[Paragraph])",
              "VAR Temptable =",
              "    ADDCOLUMNS (",
              "        ADDCOLUMNS (",
              "            SUMMARIZE ( Fatti, Fatti[area], Fatti[id_Audit], Fatti[topic], Fatti[Structural_Managerial] , Fatti[must_should], Fatti[level_of_priority], Fatti[Chapter_Value], Fatti[Paragraph]),",
              "            \"Flag\",",
              "                IF ( Fatti[topic] IN Topic_Selez && Fatti[area] IN Area_Selez && Fatti[Structural_Managerial] IN Type_managerial && Fatti[must_should] IN Must_Should && Fatti[level_of_priority] IN Priority && Fatti[Chapter_Value] IN Chapter && Fatti[Paragraph] IN Paragraph, 1, 0 ),",
              "            \"Weighted\", [Weighted Avg Score],",
              "            \"Simulation\",",
              "                CALCULATE (",
              "                    [Valore_Ponderato_What_if_scenario],",
              "                    Dimensioni[topic] IN Topic_Selez",
              "                )",
              "        ),",
              "        \"Final\", IF ( [Flag] = 1, [Valore_Ponderato_What_if_scenario], [Weighted Avg Score] )",
              "    )",
              "RETURN",
              "    IF (",
              "        'Miglioramento_%'[Miglioramento_% Value] = 0,",
              "        [Weighted Avg Score],",
              "        IF (",
              "            ISINSCOPE ( Fatti[area] ),",
              "            AVERAGEX ( Temptable, [Final] ),",
              "            AVERAGEX ( SUMMARIZE ( Temptable, [area], [topic], [Final] ), [Final] )",
              "        )",
              "    )"
            ],
            "lineageTag": "f2e58d42-d6e6-4cc1-bb25-f553b17be0b0"
          },
          {
            "name": "Flag_Topic",
            "expression": [
              "",
              "VAR Values_ =",
              "    VALUES ( Chapter_requirement[topic] )",
              "VAR Temptable =",
              "    ADDCOLUMNS (",
              "        SUMMARIZE (",
              "           Fatti,",
              "           Fatti[area],",
              "           Fatti[id_Audit],",
              "           Fatti[topic]",
              "        ),",
              "        \"Value\", IF ( Fatti[topic] IN Values_, 1, 0 )",
              "    )",
              "RETURN",
              "     MAXX ( Temptable, [Value] ) "
            ],
            "formatString": "0",
            "lineageTag": "209517f0-e244-42cc-9d9b-fc04e6edfaef"
          },
          {
            "name": "Simulation_Aggregated",
            "displayFolder": "What_If_Scenario",
            "expression": [
              "",
              "AVERAGEX(",
              "    SUMMARIZE(",
              "        Fatti,",
              "        Fatti[id_Audit],",
              "        Fatti[area],",
              "        \"Score\", [Simulated_Score_%_Final]",
              "    ), [Score])"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "dab86ad7-13c2-41d1-bd2b-f50af6ba0a9e"
          },
          {
            "name": "Structural_Managerial_Selection",
            "expression": "CONCATENATEX(VALUES(Chapter_requirement[structural_managerial]), Chapter_requirement[structural_managerial] & \" \", \",\")",
            "lineageTag": "98b3166c-10a0-4b7f-a20b-a26a71940722"
          },
          {
            "name": "Must_Should_Selection",
            "expression": "CONCATENATEX(VALUES(Chapter_requirement[must_should]), Chapter_requirement[must_should] & \" \", \",\")",
            "lineageTag": "d2bfa4f7-2c4b-4844-8b44-f28c98cf4db8"
          },
          {
            "name": "Priority_Selection",
            "expression": "CONCATENATEX(VALUES(Chapter_requirement[level_of_priority]), Chapter_requirement[level_of_priority] & \" \", \",\")",
            "lineageTag": "c4b9bbeb-508c-4d80-a837-44eddd9951a2"
          },
          {
            "name": "Area_Selection",
            "expression": "IF(ISFILTERED(Area[area]),CONCATENATEX(VALUES(Area[area]), Area[area] & \".\", UNICHAR(10)), \"All Areas\")",
            "lineageTag": "de9a4c5c-5461-4a5a-bf1f-ed343fe307a4"
          },
          {
            "name": "Hazard_Selection",
            "expression": [
              "",
              "VAR ConCat = ",
              "    CALCULATE (",
              "        CONCATENATEX (",
              "            VALUES( Hazard_Topic[Hazard] ),",
              "            Hazard_Topic[Hazard] & \".\",",
              "            UNICHAR(10)",
              "        )",
              "    )",
              "VAR IsItFiltered =",
              "    IF ( ISFILTERED ( Hazard_Topic[Hazard] ), ConCat, \"All Hazards Selected\" )",
              "RETURN",
              "   IsItFiltered"
            ],
            "lineageTag": "0292eb0e-a176-4d9e-96bb-a29aa67fdf0f"
          },
          {
            "name": "Chapter_Selection",
            "expression": [
              "",
              "VAR ConCat = ",
              "    CALCULATE (",
              "        CONCATENATEX (",
              "            VALUES(Chapter_requirement[Chapter_Conc] ),",
              "            LOWER(Chapter_requirement[Chapter_Conc])  & \".\",",
              "            UNICHAR(10)",
              "        )",
              "    )",
              "VAR IsItFiltered =",
              "    IF ( ISFILTERED ( Chapter_requirement[Chapter_Conc] ) || ISCROSSFILTERED(Chapter_requirement[Chapter_Conc]), ConCat, \"All Chapters Selected\" )",
              "RETURN",
              "   IsItFiltered"
            ],
            "lineageTag": "b1ad3eec-5023-4e11-8533-fa174d281e97"
          },
          {
            "name": "Paragraph_Selection",
            "expression": [
              "",
              "VAR ConCat = ",
              "    CALCULATE (",
              "        CONCATENATEX (",
              "            VALUES(Chapter_requirement[Paragraph] ),",
              "            LOWER(Chapter_requirement[Paragraph]) & \".\",",
              "            UNICHAR(10)",
              "        )",
              "    )",
              "VAR IsItFiltered =",
              "    IF ( ISFILTERED ( Chapter_requirement[Paragraph]) || ISCROSSFILTERED(Chapter_requirement[Paragraph]), ConCat, \"All Paragraphs Selected\" )",
              "RETURN",
              "   IsItFiltered"
            ],
            "lineageTag": "f9ecbaeb-0451-4548-90b2-474039fae01b"
          },
          {
            "name": "Year_Selection",
            "expression": [
              "",
              "VAR Count_Years =",
              "    CALCULATE(COUNTROWS(VALUES(Dimensioni[data])), FILTER(Fatti, [Report Filter] >= 1))",
              "VAR Selected_Value = ",
              "IF( Count_Years = 1, CALCULATE(VALUES(Dimensioni[data]), FILTER(Fatti, [Report Filter] >= 1)), \"More than one year selected\")",
              "RETURN",
              "IF( Count_Years = 1, Selected_Value, \"More than one year selected\")"
            ],
            "lineageTag": "de323fa5-797b-4fa9-ae31-05f8937f66e2"
          },
          {
            "name": "Weighted Avg Score_closing",
            "expression": [
              "",
              "",
              "var maxclosingdate = CALCULATE(MAX(Fatti[closing_date]),ALLEXCEPT(Fatti,Fatti[PlantCode],Fatti[subplantcode],Fatti[closing_date]), YEAR(Fatti[closing_date]) <= MAX('Year'[data]))",
              "",
              "VAR TableAux=",
              "",
              "SUMMARIZE(SUMMARIZE (",
              "    CALCULATETABLE(Fatti, REMOVEFILTERS(Dimensioni[data]),Fatti[closing_date] = maxclosingdate),",
              "        Fatti[id_Audit],",
              "        Fatti[Area],",
              "        Fatti[PlantCode],",
              "        Fatti[subplantcode],",
              "        Fatti[closing_date],",
              "        dimensioni[data],",
              "        Fatti[weight],",
              "        \"Score Aggregato per Area\", AVERAGE(Fatti[updated_conformita])",
              "    ),Fatti[PlantCode],Fatti[subplantcode],Dimensioni[data],Fatti[weight],\"Score Aggregato per Subplant\",AVERAGE(Fatti[updated_conformita]))",
              "",
              "RETURN",
              "",
              "",
              "SUMX(TableAux,[Score Aggregato per Subplant])"
            ],
            "lineageTag": "b86b687a-a87b-4d45-a672-8ad86cb18d65"
          },
          {
            "name": "Media Aritmetica_closing",
            "expression": [
              "",
              "",
              "var maxclosingdate = CALCULATE(MAX(Fatti[closing_date]),ALLEXCEPT(Fatti,Fatti[PlantCode],Fatti[subplantcode],Fatti[closing_date]), YEAR(Fatti[closing_date]) <= MAX('Year'[data]))",
              "",
              "VAR _TempTable =",
              "    SUMMARIZE (",
              "        CALCULATETABLE(Fatti, REMOVEFILTERS(Dimensioni[data]),Fatti[closing_date] = maxclosingdate),",
              "        Fatti[id_Audit],",
              "        Fatti[topic],",
              "        Fatti[key],",
              "        Fatti[Plant],",
              "        Fatti[subplantcode],",
              "        \"Media\", AVERAGE ( Fatti[valore] )",
              "    )",
              "",
              "RETURN",
              "    COUNTROWS ( _TempTable )"
            ],
            "formatString": "0",
            "lineageTag": "671736b4-863e-4b8e-aae6-0488cae87672"
          }
        ],
        "partitions": [
          {
            "name": "KPI-55cbceb3-36cc-40e3-a978-bc1f7030d3f4",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Misure = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Misure\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Misure\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Cross Analysis by Plant",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "11e147c53ca64061aef3433a26994a8a"
          }
        ],
        "columns": [
          {
            "name": "Parameter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "6dd5c3e5-fa15-4567-8930-aa5713758f09",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parameter Fields"
                }
              ]
            },
            "sortByColumn": "Parameter Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parameter Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "ee0f4fe1-c991-4a29-bdb9-f7ead79f1c29",
            "sortByColumn": "Parameter Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parameter Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "7af372bf-8010-452e-a2c2-cfd82824f9cd",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Analysis Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "c8e46712-dc59-41c5-a581-7d46f1200474",
            "sortByColumn": "Parameter Order",
            "sourceColumn": "[Value4]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "5e89188d-889b-4987-9bbf-ba7d0f18038b",
        "partitions": [
          {
            "name": "Cross Analysis by Plant-2aa45f0b-b37a-4cc8-bc74-ef684ed37e00",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Must\", NAMEOF('KPI'[Average of Value for Must]), 0, \"Must/Should\"),",
                "    (\"Should\", NAMEOF('KPI'[Average of Value for Should]), 0, \"Must/Should\"),",
                "    (\"High\", NAMEOF('KPI'[Average of Value for High]), 1, \"Priority\"),",
                "    (\"Low\", NAMEOF('KPI'[Average of Value for Low]), 1, \"Priority\"),",
                "    (\"Must + High\", NAMEOF('KPI'[Must + High]), 2, \"Cross Analysis\"),",
                "    (\"Must + Low\", NAMEOF('KPI'[Must + Low]), 2, \"Cross Analysis\")",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Miglioramento_%",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "6230e0e8c45044ce94f188b5c64bef0b"
          }
        ],
        "columns": [
          {
            "name": "Miglioramento_%",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "double",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "1e2cbdae-897f-4b39-b38f-a950dd51ccbf",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "4e27be7d-46d5-40eb-9153-4b43073a98b7",
        "measures": [
          {
            "name": "Miglioramento_% Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "SELECTEDVALUE ( 'Miglioramento_%'[Miglioramento_%], 1 )"
            ],
            "lineageTag": "f39be8a3-671a-4e10-ac9a-ac386dfc5858"
          }
        ],
        "partitions": [
          {
            "name": "Miglioramento_%-277d8f65-5aef-4005-8de4-b4ec4b28def1",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(0, 1.05, 0.05)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Investimenti",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Version",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a444cf3e-2cc5-424c-90ba-a236c0e76b5a",
            "sourceColumn": "Version",
            "summarizeBy": "none"
          },
          {
            "name": "ordinamentoVersione",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "75c4a94a-5ff0-4450-beee-6c6382ee6559",
            "sourceColumn": "ordinamentoVersione",
            "summarizeBy": "sum"
          },
          {
            "name": "Project",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f8a5e75d-5a87-46a4-8335-f56edbe00e31",
            "sourceColumn": "Project",
            "summarizeBy": "none"
          },
          {
            "name": "ProjectDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "dbb5d49e-1ba0-49f3-973f-68e8c58fecb0",
            "sourceColumn": "ProjectDescription",
            "summarizeBy": "none"
          },
          {
            "name": "Plant",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "07060c13-c67e-4e1e-b45c-b2fee3ee7470",
            "sourceColumn": "Plant",
            "summarizeBy": "none"
          },
          {
            "name": "RCAStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "5cdd7a4f-647f-4a16-ab0d-e64f2bae70a2",
            "sourceColumn": "RCAStatus",
            "summarizeBy": "none"
          },
          {
            "name": "ApprovalDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "55f3b1ed-cdcc-4e05-b4c5-7a6851decc80",
            "sourceColumn": "ApprovalDate",
            "summarizeBy": "none"
          },
          {
            "name": "StartUpDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "a46ad477-f957-481b-9b76-bb02e450975f",
            "sourceColumn": "StartUpDate",
            "summarizeBy": "none"
          },
          {
            "name": "ApprovalAmountOfRCA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "ee500151-3521-4c7d-99a1-0f25a2767d97",
            "sourceColumn": "ApprovalAmountOfRCA",
            "summarizeBy": "sum"
          },
          {
            "name": "CashOutPreviousYearsTillYearNMinus1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "8b2bb2c6-a9e1-4a6a-b8cb-cb3f1b6f8aba",
            "sourceColumn": "CashOutPreviousYearsTillYearNMinus1",
            "summarizeBy": "sum"
          },
          {
            "name": "CashOutyearNReferenceVersion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00",
            "isHidden": true,
            "lineageTag": "f9578a9e-2a9f-41bc-97ed-38710980de32",
            "sourceColumn": "CashOutyearNReferenceVersion",
            "summarizeBy": "sum"
          },
          {
            "name": "CashOutFutureYearsFromYearNPlus1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "99f1d43f-240e-4538-a837-c92a5740e29d",
            "sourceColumn": "CashOutFutureYearsFromYearNPlus1",
            "summarizeBy": "sum"
          }
        ],
        "isHidden": true,
        "lineageTag": "a64aa951-de12-4374-8fc5-0b61e3c78cbc",
        "partitions": [
          {
            "name": "Investimenti-abe09e61-1ae2-4f04-9b90-465cf1d1c988",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(dbrksHostName, dbrksHttpPath, [Catalog=null, Database=null, EnableAutomaticProxyDiscovery=null]),",
                "   hive_metastore_Database = Source{[Name=dbrksCatalog,Kind=\"Database\"]}[Data],",
                "    gmpdltdb_Schema = hive_metastore_Database{[Name=\"gmpdltdb\",Kind=\"Schema\"]}[Data],",
                "    investimenti_Table = gmpdltdb_Schema{[Name=\"investimenti\",Kind=\"View\"]}[Data]",
                "in",
                "    investimenti_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Chapter_requirement",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "69a25ad1486d44e387ed56448738bf29"
          }
        ],
        "columns": [
          {
            "name": "Chapter_Conc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ba3631d0-3a30-4867-bd00-f508364651f3",
            "sortByColumn": "Chapter_Value",
            "sourceColumn": "Dimensioni[Chapter_Conc]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Requirement_conc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d2d9bbe4-a8d7-49b8-844f-d64204b317fb",
            "sourceColumn": "Dimensioni[Requirement_conc]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Chapter_Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c4ac3ad1-1341-43a2-9f62-3a205fc13ba8",
            "sourceColumn": "Dimensioni[Chapter_Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "topic",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "7373e71c-1243-4cea-99df-75e6556a5572",
            "sourceColumn": "Dimensioni[topic]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "must_should",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c52803df-760b-4b0d-8376-53eace2cafe0",
            "sourceColumn": "Dimensioni[must_should]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "level_of_priority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "1c25a7c2-053a-4237-ba12-e4f6a9ea5378",
            "sourceColumn": "Dimensioni[level_of_priority]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "structural_managerial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "8e078aac-f516-44a0-b45b-919a4d9cbef5",
            "sourceColumn": "Dimensioni[structural_managerial]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Paragraph",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "390373d3-e9cb-4870-98c5-a5abcc702ec2",
            "sourceColumn": "Dimensioni[Paragraph]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "99e4109b-84c9-45a7-b092-13373bf5d902",
        "partitions": [
          {
            "name": "Chapter_requirement-ee77fd2b-7c6f-46d2-b169-c339690df517",
            "mode": "import",
            "source": {
              "expression": "SUMMARIZE(Dimensioni, Dimensioni[Chapter_Value], Dimensioni[Chapter_Conc], Dimensioni[Requirement_conc], Dimensioni[topic], Dimensioni[must_should], Dimensioni[level_of_priority], Dimensioni[structural_managerial], Dimensioni[Paragraph])",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Hazard_Topic",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "144c538f080446b28bbf33dc584e2f0f"
          }
        ],
        "columns": [
          {
            "name": "Hazard",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b80004d7-e1c8-4cd3-aa14-016aa2814bbc",
            "sourceColumn": "No_Hazard_Table[Hazard]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "KEY_RISK",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "d135b6e0-d127-4a6b-8432-42200815ad87",
            "sourceColumn": "No_Hazard_Table[KEY_RISK]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "f7f3d757-94b9-4380-b6f1-627aae51eed7",
        "partitions": [
          {
            "name": "Hazard_Topic-a28cf43d-09ef-488d-b4f9-8516c79b47d5",
            "mode": "import",
            "source": {
              "expression": "SUMMARIZE(No_Hazard_Table, No_Hazard_Table[Hazard], No_Hazard_Table[KEY_RISK])",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Year",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0c996964-0c28-4645-9a18-44d92a832838",
            "sourceColumn": "data",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "29fe8b71-bdcc-48e2-b5cb-e4f705da12f8",
        "partitions": [
          {
            "name": "Year",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Databricks.Catalogs(dbrksHostName, dbrksHttpPath, [Catalog=null, Database=null, EnableQueryResultDownload=\"0\", EnableExperimentalFlagsV1_1_0=null]),",
                "    eaap_gmp_prd_Database = Source{[Name=dbrksCatalog,Kind=\"Database\"]}[Data],",
                "    gmpdltdb_Schema = eaap_gmp_prd_Database{[Name=\"gmpdltdb\",Kind=\"Schema\"]}[Data],",
                "    dimensioni_View = gmpdltdb_Schema{[Name=\"dimensioni\",Kind=\"View\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dimensioni_View,{\"data\"}),",
                "    #\"Removed Duplicates\" = Table.Distinct(#\"Removed Other Columns\")",
                "in",
                "    #\"Removed Duplicates\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_c4dc0ceb-2108-4fc3-89b0-6cc04725e466",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "587e643c-f4c6-489f-9fbf-0fb306f9420e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "7372b815-7ed0-4fb2-b1d2-93915f617656",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "837b0440-0fde-4f30-b59b-efca6e0eb4ad",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "d50886a1-bd03-435c-b8b3-bfcb0b0c4d9b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "29d8cd69-8bd1-4d44-aef5-b1a90cca3462",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "497369b3-709b-4145-afcb-01099a95946c",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "3b581541-184a-4c5b-ae91-edd48bd78143",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "eed192dd-eb31-4c09-ba8c-60342281e454",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "aaba1052-de9d-4896-9a0d-6c3b7f14887c",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "f83eabd2-45ff-4239-b137-6770052e928e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "041ca298-a21b-46a0-9f48-61a07921c105",
                "ordinal": 3
              }
            ],
            "lineageTag": "6db73f4b-7f92-414d-a8d8-ebc3abcaaf35"
          }
        ],
        "isHidden": true,
        "lineageTag": "502f57d3-f5c1-4529-b10a-ab81f844211c",
        "partitions": [
          {
            "name": "LocalDateTable_c4dc0ceb-2108-4fc3-89b0-6cc04725e466",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Fatti'[closing_date])), 1, 1), Date(Year(MAX('Fatti'[closing_date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}